{% extends 'common.swig' %}
{% block banner %}
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="offset1 span10">
                <br>
                <h1>404 - FILE NOT FOUND</h1>
                <br>
                <br>
                <br>
                <p class="lead">The page you are looking for can't be found!</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}